// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search_email.sql

package database

import (
	"context"
)

const searchEmail = `-- name: SearchEmail :one

SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red, username 
              FROM users 
              WHERE email = $1
`

func (q *Queries) SearchEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, searchEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
		&i.Username,
	)
	return i, err
}
