// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_user_info.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users
SET email = $1,
    hashed_password = $2
WHERE id = $3
`

type UpdateUserInfoParams struct {
	Email          string
	HashedPassword sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
